name: sistema_ebd
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  path_provider: ^2.1.2
  http: ^1.3.0
  flutter_riverpod: ^2.6.1
  dio: ^5.8.0+1
  flutter_native_splash: ^2.4.5
  flutter_launcher_icons: ^0.14.3
  intl: ^0.20.2
  
flutter_native_splash:
  color: "#034279"  # Cor de fundo
  image: assets/images/logo_ebd.png  # Caminho para a imagem
  android: true

flutter_icons:
  android: true
  image_path: "assets/images/icone_app.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/logo_ebd.png
    - assets/images/icon_perfil.png
    - assets/images/icone_opcoes/cadastro_aula_icon.png
    - assets/images/icone_opcoes/gerenciar_classe_icon.png
    - assets/images/icone_opcoes/gerenciar_membros_icon.png
    - assets/images/icone_opcoes/registro_aula_icon.png

  uses-material-design: true


